name: ci 

on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
             - name: Checkout repo
               uses: actions/checkout@v3
             - name: Install dependencies
               run: npm install
             - name: Run test
               run: npm test
             - name: Cypress run
               uses: cypress-io/github-action@v6
               with:
                start: npm start
                wait-on: 'http://localhost:8080/docs' 
               env: 
                   BASE_URL: https://softwareengineering2projects.onrender.com/docs/
             
    cd:
        runs-on: ubuntu-latest
        needs: ci
        if: github.ref == 'refs/heads/main'
        steps:
        - name: Deploy to Render
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
              service-id: ${{ secrets.RENDER_SERVICE_ID }}
              api-key: ${{ secrets.RENDER_API_KEY }}
        
        
        
        
